# name: CI-Backend

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install modules
#         run: |
#           cd frontend
#           yarn
#       - name: Run Tests
#         run: |
#           cd frontend
#           yarn test-backend:ci
#         env:
#           SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
